version: '3.11'  # Updated version to avoid the 'obsolete' warning

services:
  web:
    build:
      context: ./backend  # Path to the directory containing the Dockerfile
      dockerfile: Dockerfile  # Ensure this matches the name of your Dockerfile
    ports:
      - "8000:8000"
    env_file:
      - .env
    volumes:
      - ./backend:/app  # Mount the backend directory
    image: django-backend

  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"

  frontend:
    build:
      context: ./frontend  # Path to the directory containing the Vue.js Dockerfile
    ports:
      - "8080:80"  # Map port 80 in the container to port 8080 on the host
    volumes:
      - ./frontend:/app  # Mount the frontend directory for live development
    environment:
      - NODE_ENV=development  # Set environment variable for development mode
    image: vue-frontend

volumes:
  postgres_data:
