FROM python:3.11-slim
WORKDIR /app
RUN apt-get update && apt-get install -y --no-install-recommends \
    build-essential gcc libpq-dev && \
    pip install --no-cache-dir pipenv && \
    apt-get clean && rm -rf /var/lib/apt/lists/*

COPY Pipfile Pipfile.lock /app/

RUN pipenv install --system --deploy
COPY ./backend /app/backend

RUN python /app/backend/manage.py collectstatic --noinput
EXPOSE 8000
# CMD ["gunicorn", "backend.core.wsgi:application", "--bind", "0.0.0.0:8000"]

# CMD ["python3", "manage.py", "runserver", "0.0.0.0:8000"]

CMD ["gunicorn", "core.wsgi:application", "--bind", "0.0.0.0:8000"]

