# Generated by Django 5.0.4 on 2024-07-28 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0002_alter_education_end_date_alter_experience_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="institution",
            field=models.CharField(default="", max_length=100),
        ),
        migrations.AddField(
            model_name="experience",
            name="company",
            field=models.CharField(default="", max_length=100),
        ),
    ]
