# Generated by Django 5.0.4 on 2024-08-30 08:26

import cv.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0011_educationimage_experienceimage"),
    ]

    operations = [
        migrations.AlterField(
            model_name="educationimage",
            name="image",
            field=models.ImageField(upload_to="education_images/"),
        ),
        migrations.AlterField(
            model_name="experienceimage",
            name="image",
            field=models.ImageField(
                upload_to="experience_images/",
                validators=[cv.validators.validate_file_size],
            ),
        ),
    ]
