# Generated by Django 5.1.4 on 2024-12-26 16:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0012_alter_educationimage_image_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageUrl",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("image_url", models.CharField(max_length=255)),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_urls",
                        to="cv.experience",
                    ),
                ),
            ],
        ),
    ]
