# Generated by Django 5.1.4 on 2024-12-26 16:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0013_imageurl"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="experience",
            name="image_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.DeleteModel(
            name="ImageUrl",
        ),
    ]
