# Generated by Django 5.0.4 on 2024-07-29 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0003_education_institution_experience_company"),
    ]

    operations = [
        migrations.AlterField(
            model_name="education",
            name="grade",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
