# Generated by Django 5.0.4 on 2024-07-29 23:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0005_education_ranking_experience_ranking"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="experience",
            name="description",
        ),
        migrations.CreateModel(
            name="ExperienceDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "experience",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="cv.experience",
                    ),
                ),
            ],
        ),
    ]
