# Generated by Django 5.0.4 on 2024-07-31 08:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0006_remove_experience_description_experiencedescription"),
    ]

    operations = [
        migrations.CreateModel(
            name="EducationDescription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.TextField()),
                (
                    "education",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="descriptions",
                        to="cv.education",
                    ),
                ),
            ],
        ),
    ]
