# Generated by Django 5.0.4 on 2024-08-09 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("cv", "0009_education_subtitle_experience_role_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="education",
            name="role",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
